"""
log_service.py -> System Logs

Future PRD area: System Logs.

Records system events into data/system_logs.json for auditing and debugging.
For Prompt 2 the key job is logging *rejected* sensor readings so there is an
audit trail of every reading the API refused (and why), without ever storing
the rejected reading in readings.json.
"""

import uuid
from datetime import datetime, timezone

from models.system_log_model import make_log
from services.storage_service import append_json, read_json


def _now_iso():
    """Current UTC time as an ISO-8601 string."""
    return datetime.now(timezone.utc).isoformat()


def _new_log_id():
    """Generate a unique log id."""
    return "LOG-" + uuid.uuid4().hex[:12]


def add_log(
    event_type,
    description,
    sensor_id=None,
    sensor_type=None,
    alert_id=None,
    actuator_id=None,
    rejection_reason=None,
    original_payload=None,
    details=None,
):
    """Create and persist a system log entry. Returns the stored entry."""
    entry = make_log(
        log_id=_new_log_id(),
        event_type=event_type,
        description=description,
        sensor_id=sensor_id,
        sensor_type=sensor_type,
        alert_id=alert_id,
        actuator_id=actuator_id,
        rejection_reason=rejection_reason,
        original_payload=original_payload,
        details=details,
        created_at=_now_iso(),
    )
    append_json("system_logs.json", entry)
    return entry


def log_alert_generated(alert_id, sensor_id, severity, alert_type):
    """Record that an alert was generated by the backend."""
    return add_log(
        event_type="alert_generated",
        description=f"{severity} alert generated ({alert_type})",
        sensor_id=sensor_id,
        alert_id=alert_id,
    )


def log_alert_resolved(alert_id, sensor_id):
    """Record that an active alert was resolved."""
    return add_log(
        event_type="alert_resolved",
        description="Alert marked as resolved",
        sensor_id=sensor_id,
        alert_id=alert_id,
    )


def log_alert_resolve_failed(alert_id, reason):
    """Record a failed attempt to resolve an alert (e.g. unknown id)."""
    return add_log(
        event_type="alert_resolve_failed",
        description=f"Alert resolve failed: {reason}",
        alert_id=alert_id,
    )


def log_alert_generation_failed(sensor_id, reading_id, reason):
    """Record that an alert could not be generated for a warning/critical reading."""
    return add_log(
        event_type="alert_generation_failed",
        description=f"Alert generation failed for reading {reading_id}: {reason}",
        sensor_id=sensor_id,
    )


def log_automation_triggered(actuator_id, alert_id, sensor_id, action_type):
    """Record that an automation response was triggered for a critical alert."""
    return add_log(
        event_type="automation_triggered",
        description=f"Automation response triggered ({action_type})",
        sensor_id=sensor_id,
        alert_id=alert_id,
        actuator_id=actuator_id,
    )


def log_actuator_status_changed(actuator_id, status, trigger_reason=None):
    """Record that an actuator's status changed."""
    description = f"Actuator status changed to {status}"
    if trigger_reason:
        description = f"{description}: {trigger_reason}"
    return add_log(
        event_type="actuator_status_changed",
        description=description,
        actuator_id=actuator_id,
    )


def log_actuator_reset(actuator_id):
    """Record that an actuator was manually reset to inactive."""
    return add_log(
        event_type="actuator_reset",
        description="Actuator reset to inactive",
        actuator_id=actuator_id,
    )


def log_automation_trigger_failed(alert_id, sensor_id, reason):
    """Record that automation could not be triggered (e.g. no matching actuator)."""
    return add_log(
        event_type="automation_trigger_failed",
        description=f"Automation trigger failed: {reason}",
        sensor_id=sensor_id,
        alert_id=alert_id,
    )


def log_unsupported_automation_rule(alert_id, sensor_id, alert_type):
    """Record that the automation service received an alert it has no rule for."""
    return add_log(
        event_type="unsupported_automation_rule",
        description=f"No automation rule for alert type '{alert_type}'",
        sensor_id=sensor_id,
        alert_id=alert_id,
    )


def log_threshold_rule_updated(sensor_type, old_rule, new_rule, role):
    """Record a successful threshold rule update (with old/new values)."""
    details = {
        "old_min_value": old_rule.get("min_value"),
        "old_max_value": old_rule.get("max_value"),
        "old_warning_margin": old_rule.get("warning_margin"),
        "new_min_value": new_rule.get("min_value"),
        "new_max_value": new_rule.get("max_value"),
        "new_warning_margin": new_rule.get("warning_margin"),
        "role": role,
    }
    return add_log(
        event_type="threshold_rule_updated",
        description=f"Threshold rule updated for {sensor_type}",
        sensor_type=sensor_type,
        details=details,
    )


def log_unauthorized_threshold_update(sensor_type, role):
    """Record a rejected threshold update due to an unauthorized role."""
    return add_log(
        event_type="unauthorized_threshold_update_attempt",
        description="Threshold update rejected: caller is not a system administrator",
        sensor_type=sensor_type,
        details={"role": role},
    )


def log_invalid_threshold_update(sensor_type, errors, role):
    """Record a rejected threshold update that failed validation."""
    return add_log(
        event_type="invalid_threshold_update_attempt",
        description="Threshold update rejected: invalid values",
        sensor_type=sensor_type,
        rejection_reason="; ".join(errors) if errors else None,
        details={"role": role, "errors": errors},
    )


def log_sensor_configuration_updated(sensor_id, sensor_type, changes, role):
    """Record a successful sensor configuration update (with old/new values)."""
    return add_log(
        event_type="sensor_configuration_updated",
        description=f"Sensor configuration updated for {sensor_id}",
        sensor_id=sensor_id,
        sensor_type=sensor_type,
        details={"role": role, "changes": changes},
    )


def log_unauthorized_sensor_update(sensor_id, role):
    """Record a rejected sensor update due to an unauthorized role."""
    return add_log(
        event_type="unauthorized_sensor_update_attempt",
        description="Sensor update rejected: caller is not a system administrator",
        sensor_id=sensor_id,
        details={"role": role},
    )


def log_invalid_sensor_update(sensor_id, errors, role):
    """Record a rejected sensor update that failed validation."""
    return add_log(
        event_type="invalid_sensor_update_attempt",
        description="Sensor update rejected: invalid values",
        sensor_id=sensor_id,
        rejection_reason="; ".join(errors) if errors else None,
        details={"role": role, "errors": errors},
    )


def log_sensor_became_inactive(sensor_id, sensor_type):
    """Record that a sensor went stale (no recent valid reading)."""
    return add_log(
        event_type="sensor_became_inactive",
        description=f"Sensor {sensor_id} became inactive (no recent valid reading)",
        sensor_id=sensor_id,
        sensor_type=sensor_type,
    )


def log_sensor_no_data(sensor_id, sensor_type):
    """Record that a sensor has not produced any valid reading yet."""
    return add_log(
        event_type="sensor_no_data",
        description=f"Sensor {sensor_id} has no data yet",
        sensor_id=sensor_id,
        sensor_type=sensor_type,
    )


def log_analytics_summary_generated():
    """Record that a dashboard analytics summary was generated."""
    return add_log(
        event_type="analytics_summary_generated",
        description="Dashboard analytics summary generated",
    )


def log_health_score_calculated(score, interpretation):
    """Record that the greenhouse health score was calculated."""
    return add_log(
        event_type="health_score_calculated",
        description=f"Greenhouse health score calculated: {score} ({interpretation})",
        details={"score": score, "interpretation": interpretation},
    )


def log_analytics_calculation_failed(reason):
    """Record that an analytics calculation failed (handled safely)."""
    return add_log(
        event_type="analytics_calculation_failed",
        description=f"Analytics calculation failed: {reason}",
    )


def log_missing_threshold_rule(sensor_id, sensor_type):
    """Record that a valid reading could not be evaluated (no threshold rule)."""
    return add_log(
        event_type="missing_threshold_rule",
        description="No threshold rule configured for sensor type; reading not stored",
        sensor_id=sensor_id,
        sensor_type=sensor_type,
    )


def log_rejected_reading(sensor_id, event_type, rejection_reason, original_payload=None):
    """
    Convenience helper to record a rejected sensor reading.

    `event_type` should be the most specific rejection reason code
    (e.g. "invalid_unit", "non_numeric_value"); `rejection_reason` is a
    human-readable summary of all problems found.
    """
    return add_log(
        event_type=event_type,
        description="Sensor reading rejected by validation",
        sensor_id=sensor_id,
        rejection_reason=rejection_reason,
        original_payload=original_payload,
    )


def log_simulation_scenario_started(scenario_id):
    """Record that a predefined simulation scenario started running."""
    return add_log(
        event_type="simulation_scenario_started",
        description=f"Simulation scenario started: {scenario_id}",
        details={"scenario_id": scenario_id},
    )


def log_simulation_scenario_completed(scenario_id):
    """Record that a simulation scenario completed successfully."""
    return add_log(
        event_type="simulation_scenario_completed",
        description=f"Simulation scenario completed: {scenario_id}",
        details={"scenario_id": scenario_id},
    )


def log_simulation_scenario_failed(scenario_id, reason):
    """Record that a simulation scenario failed to complete."""
    return add_log(
        event_type="simulation_scenario_failed",
        description=f"Simulation scenario failed: {scenario_id} ({reason})",
        details={"scenario_id": scenario_id, "reason": reason},
    )


def log_unknown_simulation_scenario(scenario_id):
    """Record that an unknown simulation scenario id was requested."""
    return add_log(
        event_type="unknown_simulation_scenario",
        description=f"Unknown simulation scenario requested: {scenario_id}",
        details={"scenario_id": scenario_id},
    )


def log_unauthorized_access_attempt(role, action, endpoint):
    """
    Record that a valid role attempted an action it is not permitted to perform.

    The role, the attempted action, and the endpoint are kept in `details` so the
    security audit trail captures who tried to do what, and where.
    """
    return add_log(
        event_type="unauthorized_access_attempt",
        description=f"Unauthorized action '{action}' attempted by role '{role}'",
        details={"role": role, "attempted_action": action, "endpoint": endpoint},
    )


def log_invalid_role_attempt(role, action, endpoint):
    """Record a request that carried a missing or unrecognised user role."""
    return add_log(
        event_type="invalid_role_attempt",
        description=f"Request for action '{action}' had a missing or invalid role",
        details={"role": role, "attempted_action": action, "endpoint": endpoint},
    )


def get_logs():
    """Return all system log entries, newest first."""
    logs = read_json("system_logs.json", default=[])
    return list(reversed(logs))
